### ISSUE TITLE
The scripts for processing raw data

### ISSUE THREAD

**Issue by zengkaipeng** [berenslab/morphvae#3]
The raw data of neurons is in form of "swc" but it seems that the scripts that transform "swc" into neuron trees and the scripts that generate walk representations is not provided here. Could you please add them into this repostitory?

**Comment by philippberens** [comment]
These are imported as part of the morphopy toolbox https://github.com/berenslab/MorphoPy

**Comment by zengkaipeng** [comment]
> These are imported as part of the morphopy toolbox https://github.com/berenslab/MorphoPy

ok i get it，thanks！
