### ISSUE TITLE
A bug in SeqEncoder

### ISSUE THREAD

**Issue by zengkaipeng** [berenslab/morphvae#4]
It seems that there is a bug in "SeqEncoder" in model.py
It's mentioned in the article that the useage of pack_padded_sequence is to solve the problem caused by different walk lengths. But In the code the pack_padded_sequence is applied to the embedding rather than the original walk. We can see the result that element [0, 0, 0] passes a Linear layer with bias is not always [0, 0, 0] which means the pack_padded_sequence can't pack the sequences with different lengths correctly.

**Comment by zengkaipeng** [comment]
I'm sorry that i misunderstand the meaning of the parameters in api pack_padded_sequence

**Comment by Visdoom** [comment]
Hi @zengkaipeng,

Thanks for your interest and for reaching out. No worries. If you have any more questions please don't hesitate to ask. The more eyes the better!
